### ISSUE TITLE
I wish to use subjectkeyidentifier instead of mail

### ISSUE THREAD

**Issue by usethe23** [pdias/SamlBundle#9]
I wish to use the subjectkeyidentifier instead of mail

What changes should i do to make this work ?

```
# app/config/config.yml

saml:
    service_provider: 'default-sp'
    autoload_path: '/var/simplesamlphp/lib/_autoload.php'
    authentication_field: 'http://schemas.microsoft.com/2012/12/certificatecontext/extension/subjectkeyidentifier'

```
This is what i get from simplesamlphp when i use the autoload alone with php :
```
Array
(
    [http://schemas.microsoft.com/2012/12/certificatecontext/extension/subjectkeyidentifier] => Array
        (
            [0] => username1980
        )

    [http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress] => Array
        (
            [0] => firstname.lastname@test.com
        )

    [http://schemas.xmlsoap.org/claims/CommonName] => Array
        (
            [0] => FirstName LastName
        )

    [http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn] => Array
        (
            [0] => firstname.lastname@test.com
        )

    [uid] => Array
        (
            [0] => utest
        )

)
```

This is the error that i get :

`The routing file "/var/www/html/symfony/vendor/pdias/saml-bundle/PDias/SamlBundle/Resources/config/routing.yml" contains unsupported keys for "saml_login": "pattern". Expected one of: "resource", "type", "prefix", "path", "host", "schemes", "methods", "defaults", "requirements", "options", "condition" in /var/www/html/symfony/vendor/pdias/saml-bundle/PDias/SamlBundle/Resources/config/routing.yml (which is being imported from "/var/www/html/symfony/app/config/routing.yml").`

Many thanks,
